[REFACTOR] 회원가입, 검색 결과 리스트 수정
Multi-KODI/KODI_project pull request #131
Opened 2024-02-07 09:46 UTC by hajin0607

수정목록
1. 이메일 입력칸이 있고 회원가입 버튼이 있는데
이메일을 입력하고 회원가입 버튼을 누르면
해당 이메일이 회원가입에 미리 기입되어 있지 않음

2. 관리자도 같이 검색됨

2024-02-08 00:41 UTC, YGIEN approved these changes

2024-02-08 02:06 UTC, eunsoni approved these changes

2024-02-08 02:19 UTC, PGH322 requested changes
백엔드 부분 제외해서 pr 재요청 부탁드립니다

2024-02-08 04:42 UTC, eunsoni approved these changes

2024-02-13 00:42 UTC, eunsoni approved these changes

2024-02-13 00:43 UTC, meizzi04 approved these changes

2024-02-13 00:49 UTC, PGH322 approved these changes

2024-02-13 00:49 UTC, merged